In [2]:
# TensorFlow and tf.keras
import tensorflow as tf
import numpy as np
from tensorflow import keras

#tf version should be 2.5 or higher
tf.__version__

'2.17.0'

In [3]:
#get data
(train_images, train_labels), (test_images, test_labels) = \
      keras.datasets.mnist.load_data()

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [4]:
#scale model
train_images = train_images / 255.0
test_images = test_images / 255.0

In [27]:
#setup model
model = keras.Sequential([
    keras.layers.Conv2D(kernel_size=3, filters=12, activation='relu', padding='same', input_shape=(28, 28, 1)),
    # keras.layers.MaxPooling2D(pool_size=(2, 2)),
    
    keras.layers.Conv2D(kernel_size=6, filters=24, activation='relu', padding='same', strides=2),
    # keras.layers.MaxPooling2D(pool_size=(2, 2)),
    
    keras.layers.Conv2D(kernel_size=6, filters=32, activation='relu', padding='same', strides=2),
    
    keras.layers.Flatten(),
    
    keras.layers.Dense(200, activation='relu'),
    keras.layers.Dropout(0.6),
    keras.layers.Dense(10, activation='softmax')
])

In [28]:
#compile model
model.compile(optimizer='adam',
          loss='sparse_categorical_crossentropy',
          metrics=['accuracy'])

In [29]:
#train model
model.fit(train_images, train_labels, epochs=7)

Epoch 1/7
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 64s 32ms/step - accuracy: 0.8725 - loss: 0.4007
Epoch 2/7
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 60s 32ms/step - accuracy: 0.9773 - loss: 0.0740
Epoch 3/7
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 59s 32ms/step - accuracy: 0.9827 - loss: 0.0540
Epoch 4/7
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 59s 32ms/step - accuracy: 0.9886 - loss: 0.0375
Epoch 5/7
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 59s 32ms/step - accuracy: 0.9904 - loss: 0.0322
Epoch 6/7
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 59s 32ms/step - accuracy: 0.9918 - loss: 0.0254
Epoch 7/7
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 59s 31ms/step - accuracy: 0.9935 - loss: 0.0205


In [30]:
#evaluate
test_loss, test_acc = model.evaluate(test_images,  test_labels)
print('\nTest accuracy:', test_acc)

313/313 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.9916 - loss: 0.0269

Test accuracy: 0.9937000274658203


In [31]:
# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 244ms/step


In [32]:
#Raw predictions
predictions

array([[4.20822882e-13, 7.59263652e-10, 3.60256625e-09, 3.37863987e-10,
        1.04127505e-11, 2.41549619e-12, 2.81557299e-16, 9.99998569e-01,
        2.46302501e-12, 1.39563235e-06],
       [2.07015698e-12, 4.83301482e-14, 1.00000000e+00, 1.94453958e-12,
        5.42186684e-13, 4.17925394e-17, 1.27713392e-13, 5.08323818e-14,
        9.22946547e-14, 2.65116315e-15],
       [5.35906342e-09, 9.99995112e-01, 1.45799191e-07, 9.63804370e-10,
        1.20470088e-06, 4.90430693e-07, 7.75480203e-07, 1.50653125e-06,
        4.09098959e-07, 3.13816969e-07],
       [9.99999642e-01, 3.78877532e-14, 1.34239453e-10, 2.01672012e-12,
        5.01953312e-10, 1.52993118e-10, 2.30667197e-07, 2.06060946e-10,
        2.03173728e-10, 6.00348855e-08],
       [2.56671268e-12, 5.04822073e-10, 4.87827279e-10, 3.54863789e-13,
        9.99980330e-01, 1.82132132e-09, 2.03606332e-09, 1.34724717e-10,
        2.68202314e-08, 1.96248820e-05]], dtype=float32)

In [33]:
# Print our model's predictions
print(np.argmax(predictions, axis=1))

[7 2 1 0 4]


In [34]:
# Check our predictions against the ground truths
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[7 2 1 0 4]
