In [1]:
# TensorFlow and tf.keras
import tensorflow as tf
import numpy as np

#tf version should be 2.5 or higher
tf.__version__

'2.10.0'

In [2]:
gpus = tf.config.experimental.list_physical_devices('GPU')
# List all physical devices recognized by TensorFlow
physical_devices = tf.config.list_physical_devices('GPU')
print("Available GPUs:", physical_devices)
if gpus :
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
        tf.config.experimental.set_virtual_device_configuration(gpus[0],[tf.config.experimental.VirtualDeviceConfiguration(memory_limit=1024 * 20)])

    except RuntimeError as e:
        print(e)

Available GPUs: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [3]:
from tensorflow import keras


In [4]:
#get data
(train_images, train_labels), (test_images, test_labels) = \
      keras.datasets.mnist.load_data()

In [5]:
#scale model
train_images = train_images / 255.0
test_images = test_images / 255.0

In [6]:
#setup model
model = keras.Sequential([
    keras.layers.Conv2D(kernel_size=3, filters=12, activation='relu', padding='same', input_shape=(28, 28, 1)),
    # keras.layers.MaxPooling2D(pool_size=(2, 2)),
    
    keras.layers.Conv2D(kernel_size=6, filters=24, activation='relu', padding='same', strides=2),
    # keras.layers.MaxPooling2D(pool_size=(2, 2)),
    
    keras.layers.Conv2D(kernel_size=6, filters=32, activation='relu', padding='same', strides=2),
    
    keras.layers.Flatten(),
    
    keras.layers.Dense(200, activation='relu'),
    keras.layers.Dropout(0.6),
    keras.layers.Dense(10, activation='softmax')
])

In [7]:
#compile model
model.compile(optimizer='adam',
          loss='sparse_categorical_crossentropy',
          metrics=['accuracy'])

In [19]:
#train model
# tf.debugging.set_log_device_placement(True)

model.fit(train_images, train_labels, epochs=1, batch_size=64896)


1/1 [==============================] - 1s 667ms/step - loss: 0.0012 - accuracy: 0.9997


In [21]:
#evaluate
test_loss, test_acc = model.evaluate(test_images,  test_labels, batch_size=64896)
print('\nTest accuracy:', test_acc)

1/1 [==============================] - 0s 310ms/step - loss: 0.0343 - accuracy: 0.9933

Test accuracy: 0.9933000206947327


In [8]:
# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

1/1 [==============================] - 0s 392ms/step


In [9]:
#Raw predictions
predictions

array([[1.37157993e-12, 8.01287481e-10, 4.38183351e-10, 1.88235053e-10,
        3.33292833e-12, 5.06252484e-13, 1.24550729e-16, 1.00000000e+00,
        6.12383354e-13, 5.82733917e-10],
       [6.69947500e-11, 6.06398320e-10, 1.00000000e+00, 2.36641327e-12,
        6.42975690e-12, 1.30581970e-14, 2.91178246e-08, 5.18496216e-13,
        4.98061210e-11, 6.34161339e-16],
       [3.02689059e-12, 1.00000000e+00, 2.08374806e-09, 2.00891482e-13,
        8.33684499e-09, 2.56226068e-10, 2.14777547e-08, 6.40042552e-09,
        4.48122206e-10, 6.85141527e-12],
       [1.00000000e+00, 4.90038376e-15, 2.27507059e-13, 1.44775386e-13,
        2.51662298e-12, 5.98857335e-13, 1.38623135e-09, 1.79606742e-12,
        2.28247039e-11, 1.48883184e-10],
       [9.25158833e-17, 3.72499297e-12, 9.26749725e-14, 3.60917993e-17,
        1.00000000e+00, 5.89743505e-14, 4.39200369e-12, 8.81491806e-14,
        1.36410605e-11, 4.81112181e-08]], dtype=float32)

In [33]:
# Print our model's predictions
print(np.argmax(predictions, axis=1))

[7 2 1 0 4]


In [34]:
# Check our predictions against the ground truths
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[7 2 1 0 4]


In [23]:
# Evaluations
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 28, 28, 12)        120       
                                                                 
 conv2d_1 (Conv2D)           (None, 14, 14, 24)        10392     
                                                                 
 conv2d_2 (Conv2D)           (None, 7, 7, 32)          27680     
                                                                 
 flatten (Flatten)           (None, 1568)              0         
                                                                 
 dense (Dense)               (None, 200)               313800    
                                                                 
 dropout (Dropout)           (None, 200)               0         
                                                                 
 dense_1 (Dense)             (None, 10)                2