In [1]:
# TensorFlow and tf.keras
import tensorflow as tf
import numpy as np
from tensorflow import keras

#tf version should be 2.5 or higher
tf.__version__

'2.9.0'

In [2]:
#get data
(train_images, train_labels), (test_images, test_labels) = \
      keras.datasets.mnist.load_data()

In [3]:
#scale model
train_images = train_images / 255.0
test_images = test_images / 255.0

In [4]:
#setup model
model = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(10, activation = tf.nn.softmax)
])

In [5]:
#compile model
model.compile(optimizer='sgd',
          loss='sparse_categorical_crossentropy',
          metrics=['accuracy'])

In [6]:
#train model
model.fit(train_images, train_labels, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 1ms/step - loss: 0.7860 - accuracy: 0.8122
Epoch 2/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.4564 - accuracy: 0.8806
Epoch 3/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.4034 - accuracy: 0.8914
Epoch 4/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3766 - accuracy: 0.8965
Epoch 5/5
1875/1875 [==============================] - 2s 1ms/step - loss: 0.3600 - accuracy: 0.9004


In [7]:
#evaluate
test_loss, test_acc = model.evaluate(test_images,  test_labels)
print('\nTest accuracy:', test_acc)

313/313 [==============================] - 1s 1ms/step - loss: 0.3353 - accuracy: 0.9089

Test accuracy: 0.9089000225067139


In [8]:
# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

1/1 [==============================] - 0s 45ms/step


In [9]:
#Raw predictions
predictions

array([[1.9424158e-04, 8.8084090e-07, 1.8245341e-04, 1.3522771e-03,
        4.1335992e-05, 6.6838140e-05, 2.4950436e-06, 9.9501210e-01,
        1.3676446e-04, 3.0105230e-03],
       [2.1001384e-02, 3.1138121e-04, 8.4097958e-01, 2.9657977e-02,
        9.1363654e-07, 1.9103348e-02, 7.8997590e-02, 3.9431063e-07,
        9.9431397e-03, 4.1861354e-06],
       [2.2360485e-04, 9.4543111e-01, 1.6295347e-02, 8.2478281e-03,
        8.8531274e-04, 2.8670663e-03, 6.2431335e-03, 5.9023658e-03,
        1.1816666e-02, 2.0876371e-03],
       [9.9552661e-01, 3.9075768e-08, 3.6670186e-04, 9.3957853e-05,
        8.1022137e-07, 2.2326782e-03, 1.0642521e-03, 4.3341055e-04,
        1.9519925e-04, 8.6294203e-05],
       [2.5469239e-03, 3.5345616e-05, 1.5215246e-02, 1.0329316e-03,
        8.5696644e-01, 1.6307286e-03, 1.0203900e-02, 2.5525806e-02,
        1.3813258e-02, 7.3029459e-02]], dtype=float32)

In [10]:
# Print our model's predictions
print(np.argmax(predictions, axis=1))

[7 2 1 0 4]


In [11]:
# Check our predictions against the ground truths
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[7 2 1 0 4]
